version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    depends_on:
      - mongo
    volumes:
      - ./test/config.json:/src/lib/config/config.json
  mongo:
    image: mongo:3.6.3
    expose:
      - "27017"
    logging:
      driver: none
