version: '3'

services:
  bot:
    container_name: bot
    build:
      context: .
      dockerfile: Dockerfile.Dev
    depends_on:
      - mongo
    volumes:
      - ./lib/config/config.json:/src/lib/config/config.json
      - ./tmp:/tmp
  mongo:
    container_name: mongo
    image: mongo:3.6.3
    ports:
      - "28000:27017"
    logging:
      driver: none
